# Generated by Django 5.2.3 on 2025-07-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_snippet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='access',
            field=models.CharField(choices=[('public', 'Публичный'), ('private', 'Частный')], default='public', max_length=30),
        ),
    ]
