# Generated by Django 5.2.3 on 2025-09-16 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_snippet_mainapp_sni_name_48c470_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='MainApp_not_recipie_7c69f4_idx'),
        ),
    ]
